package:
  name: fast-hdbscan
  version: 0.1.3
  top-level:
    - fast_hdbscan
requirements:
  host:
    - setuptools
  run:
    - numpy
    - numba
    - scikit-learn
source:
  url: https://files.pythonhosted.org/packages/a9/ea/c802b26c733a99476c1eae847a394e2c0e13d250073c63961823fe3c6be0/fast_hdbscan-0.1.3.tar.gz
  sha256: 49c4cee594a5128136457d128a0cd470b3fddbb9cb095c2c4b3a954392cb28c2
about:
  home: https://github.com/TutteInstitute/fast_hdbscan
  PyPI: https://pypi.org/project/fast-hdbscan
  summary: A fast multicore version of hdbscan for low dimensional euclidean spaces
  license: BSD 2-Clause License
extra:
  recipe-maintainers:
    - type9
